# Generated by Django 3.2.9 on 2021-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='qunit',
            field=models.CharField(default='kuntal', max_length=10),
        ),
    ]
