# Generated by Django 3.2.9 on 2021-11-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amounts_paid',
            new_name='amountsPaid',
        ),
        migrations.AddField(
            model_name='order',
            name='inOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='outOrder',
            field=models.BooleanField(default=False),
        ),
    ]
