# Generated by Django 3.2.9 on 2021-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211106_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cquantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
