# Generated by Django 3.2.9 on 2021-11-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cquantity',
        ),
    ]
