# Generated by Django 3.2.9 on 2021-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cquantity',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
