# Generated by Django 3.2.9 on 2021-11-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_stock_cquantity'),
        ('order', '0005_order_cquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inOrder', models.BooleanField(default=False)),
                ('outOrder', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product')),
            ],
        ),
    ]
