# Generated by Django 3.2.9 on 2021-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordertest_licenceplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertest',
            name='licencePlate',
            field=models.IntegerField(null=True),
        ),
    ]
