# Generated by Django 3.2.9 on 2021-11-12 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20211111_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencePlate', models.IntegerField()),
                ('tinNumber', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default='0', max_length=20, null=True)),
                ('price', models.PositiveIntegerField(default='0', max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderTest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='order',
            name='licencePlate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tinNumber',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderdetail'),
        ),
    ]
