# Generated by Django 3.2.9 on 2021-11-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_orderdetail_licenceplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
