# Generated by Django 3.2.9 on 2021-11-13 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderdetail_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='orderDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
