# Generated by Django 3.2.9 on 2021-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderdetail_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amountsPaid',
            field=models.PositiveIntegerField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cquantity',
            field=models.PositiveIntegerField(default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default='0', max_length=20, null=True),
        ),
    ]
