# Generated by Django 3.2.9 on 2021-11-14 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20211114_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='orderDate',
        ),
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
