# Generated by Django 3.2.9 on 2021-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20211115_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amountsPaid',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cquantity',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
    ]
